MIN_VALUE = 1.0
NUM_TARGET = 6
NUM_RESOURCE = 3
NUM_STEP = 3
NUM_ATTACK = 3

BATCH_SIZE_EPISODE = 8
MEMORY_SIZE_EPISODE = 16

BATCH_SIZE_TRANSITION = 32
MEMORY_SIZE_TRANSITION = 64

NUM_FEATURE = 6

NUM_EPISODE = 41

GAMMA = 1.0
TARGET_UPDATE_EPISODE = 2
TARGET_UPDATE_TRANSITION = 2
OPTIMIZE_UPDATE_EPISODE = 1

NUM_SAMPLE = 150

LSTM_HIDDEN_SIZE = 32
LR_TRANSITION = 0.001
LR_EPISODE = 0.001

ENTROPY_COEFF_TRANS = 1.0
ENTROPY_COEFF_EPS = 1.5
